/**
 * AI Panchayat Kendra: the reasoning engine.
 *
 * Everything in this file is real and runs in the browser with no network call:
 *
 *  1. A multinomial Naive Bayes classifier that is *trained at page load* on the
 *     labelled corpus below (Laplace-smoothed counts, log-space scoring,
 *     length-normalised softmax for a calibrated confidence).
 *  2. A script-normalising tokenizer so Devanagari, Hinglish and English land in
 *     the same feature space.
 *  3. A rule-based entity extractor (durations, amounts, documents, schemes).
 *  4. A checks engine that really evaluates each eligibility rule and each
 *     root-cause probe against the citizen's record, and returns
 *     pass / fail / unknown, never a guess.
 *  5. A routing policy that decides department, SLA and, critically, whether a
 *     human panchayat member must approve before anything moves.
 *
 * What is NOT real: the sentences the assistant speaks back. Those are templated
 * from the engine's output, not generated by a language model. The decisions are
 * the engine's; only the phrasing is scripted. The UI says so out loud.
 */

import { sha256 } from './blockchain';

/* ------------------------------------------------------------------ intents */

export type IntentId =
  | 'PENSION_FAILURE'
  | 'LAND_RECORD_ERROR'
  | 'WATER_SUPPLY'
  | 'RATION_CARD'
  | 'MGNREGA_WAGES'
  | 'HOUSING_SCHEME'
  | 'ELECTRICITY'
  | 'CERTIFICATE'
  | 'LAND_DISPUTE'
  | 'HEALTH_CARE';

export interface IntentMeta {
  id: IntentId;
  label: string;
  hindi: string;
  icon: string;
  department: string;
  officer: string;
  slaDays: number;
  /** Some case classes may never be decided by software, however confident it is. */
  neverAutomatic: boolean;
  blurb: string;
}

export const INTENTS: Record<IntentId, IntentMeta> = {
  PENSION_FAILURE: {
    id: 'PENSION_FAILURE', label: 'Pension not received', hindi: 'पेंशन नहीं मिली', icon: '👵',
    department: 'Block Social Welfare Office', officer: 'Block Social Welfare Officer',
    slaDays: 7, neverAutomatic: false,
    blurb: 'A sanctioned pension has stopped reaching the beneficiary, usually a bank-seeding or life-certificate failure, not a rejection.',
  },
  LAND_RECORD_ERROR: {
    id: 'LAND_RECORD_ERROR', label: 'Land record error', hindi: 'भूमि रिकॉर्ड में गलती', icon: '📜',
    department: 'Tehsil Revenue Office', officer: 'Tehsildar (Revenue)',
    slaDays: 21, neverAutomatic: false,
    blurb: 'A mutation, khasra or khatauni entry does not match reality. Correctable on record, but only by the revenue officer.',
  },
  WATER_SUPPLY: {
    id: 'WATER_SUPPLY', label: 'Water supply problem', hindi: 'पानी की समस्या', icon: '🚰',
    department: 'Jal Jeevan / PHED Sub-division', officer: 'Junior Engineer (Water)',
    slaDays: 3, neverAutomatic: false,
    blurb: 'Handpump, tap connection or tanker failure. Short SLA because it is a daily-survival service.',
  },
  RATION_CARD: {
    id: 'RATION_CARD', label: 'Ration / PDS issue', hindi: 'राशन की समस्या', icon: '🌾',
    department: 'Block Supply Office', officer: 'Supply Inspector',
    slaDays: 10, neverAutomatic: false,
    blurb: 'Card not issued, a name missing, or the fair-price shop short-weighing or refusing entitlement.',
  },
  MGNREGA_WAGES: {
    id: 'MGNREGA_WAGES', label: 'MGNREGA work or wages', hindi: 'मनरेगा मजदूरी', icon: '⛏️',
    department: 'Block Development Office (MGNREGA cell)', officer: 'Programme Officer, MGNREGA',
    slaDays: 15, neverAutomatic: false,
    blurb: 'Job card, work demand, or wages unpaid past the 15-day statutory limit, which itself triggers a delay-compensation claim.',
  },
  HOUSING_SCHEME: {
    id: 'HOUSING_SCHEME', label: 'Housing scheme (PMAY-G)', hindi: 'आवास योजना', icon: '🏠',
    department: 'Block Development Office (Awas cell)', officer: 'Awas Supervisor',
    slaDays: 30, neverAutomatic: false,
    blurb: 'Application, instalment or permanent-wait-list grievance under Pradhan Mantri Awas Yojana (Gramin).',
  },
  ELECTRICITY: {
    id: 'ELECTRICITY', label: 'Electricity problem', hindi: 'बिजली की समस्या', icon: '💡',
    department: 'DISCOM Sub-station', officer: 'Junior Engineer (Distribution)',
    slaDays: 3, neverAutomatic: false,
    blurb: 'Outage, transformer failure, wrong billing, or a new connection still pending.',
  },
  CERTIFICATE: {
    id: 'CERTIFICATE', label: 'Certificate needed', hindi: 'प्रमाण पत्र', icon: '🧾',
    department: 'Tehsil e-District Counter', officer: 'Naib Tehsildar',
    slaDays: 14, neverAutomatic: false,
    blurb: 'Income, caste, residence, birth or death certificate: the documents every other scheme asks for first.',
  },
  LAND_DISPUTE: {
    id: 'LAND_DISPUTE', label: 'Dispute between parties', hindi: 'आपसी विवाद', icon: '⚖️',
    department: 'Gram Panchayat bench', officer: 'Sarpanch & elected members',
    slaDays: 45, neverAutomatic: true,
    blurb: 'A boundary, inheritance or neighbour dispute. Two sides, contested facts, and a decision that changes rights. Software may summarise it, never settle it.',
  },
  HEALTH_CARE: {
    id: 'HEALTH_CARE', label: 'Health / Ayushman', hindi: 'स्वास्थ्य', icon: '🏥',
    department: 'Community Health Centre', officer: 'Ayushman Mitra / Medical Officer',
    slaDays: 2, neverAutomatic: false,
    blurb: 'Treatment refused, Ayushman card not working, or an ASHA-referred case needing transport.',
  },
};

export const INTENT_IDS = Object.keys(INTENTS) as IntentId[];

/* ------------------------------------------------------------------- corpus */

/**
 * The training set. Deliberately small and visible: 120 lines a villager might
 * actually say, in Hinglish, English and Hindi. The classifier running in the
 * demo is trained on exactly this and nothing else, and the leave-one-out score
 * you can run from the side panel is measured on exactly this.
 */
export const CORPUS: { text: string; intent: IntentId }[] = [
  // PENSION_FAILURE
  { text: 'pension nahi aa rahi 3 mahine se', intent: 'PENSION_FAILURE' },
  { text: 'meri vridha pension band ho gayi hai', intent: 'PENSION_FAILURE' },
  { text: 'widow pension has not come since january', intent: 'PENSION_FAILURE' },
  { text: 'vidhwa pension ka paisa khate mein nahi aaya', intent: 'PENSION_FAILURE' },
  { text: 'old age pension stopped bank account mein kuch nahi aaya', intent: 'PENSION_FAILURE' },
  { text: 'पेंशन नहीं आ रही है चार महीने से', intent: 'PENSION_FAILURE' },
  { text: 'buzurg pension ki kist nahi mili', intent: 'PENSION_FAILURE' },
  { text: 'my mother pension amount is not credited', intent: 'PENSION_FAILURE' },

  // LAND_RECORD_ERROR
  { text: 'khatauni mein mera naam galat likha hai', intent: 'LAND_RECORD_ERROR' },
  { text: 'land record mein rakba galat hai', intent: 'LAND_RECORD_ERROR' },
  { text: 'mutation nahi hua pita ji ke baad', intent: 'LAND_RECORD_ERROR' },
  { text: 'khasra number is wrong in the land record', intent: 'LAND_RECORD_ERROR' },
  { text: 'jameen ka record online galat dikha raha hai', intent: 'LAND_RECORD_ERROR' },
  { text: 'भूमि रिकॉर्ड में नाम गलत है सुधार करवाना है', intent: 'LAND_RECORD_ERROR' },
  { text: 'patta correction chahiye naam ki spelling galat hai', intent: 'LAND_RECORD_ERROR' },
  { text: 'namantaran application pending hai tehsil mein', intent: 'LAND_RECORD_ERROR' },

  // WATER_SUPPLY
  { text: 'gaon ka handpump kharab hai paani nahi aata', intent: 'WATER_SUPPLY' },
  { text: 'nal se paani nahi aa raha 10 din se', intent: 'WATER_SUPPLY' },
  { text: 'water supply band hai tanker bhejiye', intent: 'WATER_SUPPLY' },
  { text: 'peene ka paani ganda aa raha hai', intent: 'WATER_SUPPLY' },
  { text: 'हैंडपंप खराब है पानी की समस्या है', intent: 'WATER_SUPPLY' },
  { text: 'jal jeevan ka connection abhi tak nahi laga', intent: 'WATER_SUPPLY' },
  { text: 'no drinking water in our hamlet since a week', intent: 'WATER_SUPPLY' },
  { text: 'borewell sookh gaya paani ka intezaam kariye', intent: 'WATER_SUPPLY' },

  // RATION_CARD
  { text: 'ration card mein bete ka naam nahi juda', intent: 'RATION_CARD' },
  { text: 'kotedar poora anaj nahi de raha hai', intent: 'RATION_CARD' },
  { text: 'ration nahi mil raha do mahine se', intent: 'RATION_CARD' },
  { text: 'naya ration card apply karna hai', intent: 'RATION_CARD' },
  { text: 'राशन कार्ड में नाम नहीं जुड़ा है', intent: 'RATION_CARD' },
  { text: 'fair price shop refused to give wheat', intent: 'RATION_CARD' },
  { text: 'ration dukan par kam tolta hai galat hai', intent: 'RATION_CARD' },
  { text: 'card cancel ho gaya anaj band hai', intent: 'RATION_CARD' },

  // MGNREGA_WAGES
  { text: 'narega ki mazdoori nahi mili 40 din se', intent: 'MGNREGA_WAGES' },
  { text: 'job card banwana hai kaam chahiye', intent: 'MGNREGA_WAGES' },
  { text: 'mgnrega wages are pending for one month', intent: 'MGNREGA_WAGES' },
  { text: 'manrega mein kaam maanga tha nahi mila', intent: 'MGNREGA_WAGES' },
  { text: 'मनरेगा की मजदूरी नहीं मिली', intent: 'MGNREGA_WAGES' },
  { text: 'muster roll mein hazri nahi chadhi', intent: 'MGNREGA_WAGES' },
  { text: 'hundred days work demand under nrega', intent: 'MGNREGA_WAGES' },
  { text: 'job card hai par mazdoori ka paisa nahi aaya', intent: 'MGNREGA_WAGES' },

  // HOUSING_SCHEME
  { text: 'awas yojana ka paisa nahi aaya', intent: 'HOUSING_SCHEME' },
  { text: 'pm awas ki list mein naam nahi hai', intent: 'HOUSING_SCHEME' },
  { text: 'ghar banane ke liye kist chahiye', intent: 'HOUSING_SCHEME' },
  { text: 'pmay gramin application status kya hai', intent: 'HOUSING_SCHEME' },
  { text: 'आवास योजना में नाम जुड़वाना है', intent: 'HOUSING_SCHEME' },
  { text: 'kaccha makan hai pakka ghar ki scheme chahiye', intent: 'HOUSING_SCHEME' },
  { text: 'housing instalment second one not released', intent: 'HOUSING_SCHEME' },
  { text: 'awas ki dusri kist ruki hui hai', intent: 'HOUSING_SCHEME' },

  // ELECTRICITY
  { text: 'bijli nahi aa rahi teen din se', intent: 'ELECTRICITY' },
  { text: 'transformer jal gaya gaon mein andhera hai', intent: 'ELECTRICITY' },
  { text: 'bijli ka bill bahut zyada aaya galat hai', intent: 'ELECTRICITY' },
  { text: 'new electricity connection application is pending', intent: 'ELECTRICITY' },
  { text: 'बिजली नहीं आ रही ट्रांसफार्मर खराब है', intent: 'ELECTRICITY' },
  { text: 'light ka khamba gir gaya khatra hai', intent: 'ELECTRICITY' },
  { text: 'power cut for two days there is no supply', intent: 'ELECTRICITY' },
  { text: 'meter kharab hai bijli bill sudhar karo', intent: 'ELECTRICITY' },

  // CERTIFICATE
  { text: 'aay praman patra banwana hai', intent: 'CERTIFICATE' },
  { text: 'income certificate chahiye scholarship ke liye', intent: 'CERTIFICATE' },
  { text: 'jaati praman patra ke liye apply karna hai', intent: 'CERTIFICATE' },
  { text: 'caste certificate application pending at tehsil', intent: 'CERTIFICATE' },
  { text: 'niwas praman patra ki zarurat hai', intent: 'CERTIFICATE' },
  { text: 'जन्म प्रमाण पत्र बनवाना है बच्चे का', intent: 'CERTIFICATE' },
  { text: 'birth certificate for my child is not issued', intent: 'CERTIFICATE' },
  { text: 'mrityu praman patra chahiye pension ke liye', intent: 'CERTIFICATE' },

  // LAND_DISPUTE
  { text: 'padosi ne meri jameen par kabza kar liya', intent: 'LAND_DISPUTE' },
  { text: 'khet ki medh ko lekar jhagda ho raha hai', intent: 'LAND_DISPUTE' },
  { text: 'bhai ne hissa nahi diya batwara nahi hua', intent: 'LAND_DISPUTE' },
  { text: 'boundary dispute with neighbour over the field', intent: 'LAND_DISPUTE' },
  { text: 'पड़ोसी से जमीन का विवाद है', intent: 'LAND_DISPUTE' },
  { text: 'raste ko lekar do parivaron mein vivad hai', intent: 'LAND_DISPUTE' },
  { text: 'property partition quarrel between two brothers', intent: 'LAND_DISPUTE' },
  { text: 'chacha ne zameen bech di bina puche jhagda hai', intent: 'LAND_DISPUTE' },

  // HEALTH_CARE
  { text: 'ayushman card se ilaj nahi kar rahe', intent: 'HEALTH_CARE' },
  { text: 'aspatal ne bharti karne se mana kar diya', intent: 'HEALTH_CARE' },
  { text: 'hospital refused treatment under ayushman', intent: 'HEALTH_CARE' },
  { text: 'ambulance nahi mili delivery ke waqt', intent: 'HEALTH_CARE' },
  { text: 'आयुष्मान कार्ड नहीं बना इलाज कराना है', intent: 'HEALTH_CARE' },
  { text: 'dawa nahi mili health centre par', intent: 'HEALTH_CARE' },
  { text: 'bimar hun doctor nahi aata phc mein', intent: 'HEALTH_CARE' },
  { text: 'operation ka kharcha nahi utha sakte madad chahiye', intent: 'HEALTH_CARE' },

  // A second pass over every class. Deliberately overlapping vocabulary with the
  // block above: it is what stops a single distinctive word from being the only
  // thing holding a class up, which is visible in the leave-one-out score.
  { text: 'pension ka paisa 6 mahine se nahi mila', intent: 'PENSION_FAILURE' },
  { text: 'vridha pension khate mein nahi aa rahi', intent: 'PENSION_FAILURE' },
  { text: 'meri pension band hai bank gaya tha pata nahi chala', intent: 'PENSION_FAILURE' },
  { text: 'widow pension stopped six months ago no credit in the account', intent: 'PENSION_FAILURE' },

  { text: 'khatauni mein rakba galat hai sudhar chahiye', intent: 'LAND_RECORD_ERROR' },
  { text: 'jameen ka namantaran nahi hua record galat hai', intent: 'LAND_RECORD_ERROR' },
  { text: 'khasra khatauni mein naam galat likha hai tehsil gaya tha', intent: 'LAND_RECORD_ERROR' },
  { text: 'land record mutation is pending at the tehsil office', intent: 'LAND_RECORD_ERROR' },

  { text: 'paani ka nal kharab hai handpump bhi nahi chal raha', intent: 'WATER_SUPPLY' },
  { text: 'gaon mein peene ka paani nahi hai tanker chahiye', intent: 'WATER_SUPPLY' },
  { text: 'jal jeevan ka nal laga par paani nahi aata', intent: 'WATER_SUPPLY' },
  { text: 'drinking water supply is broken in our village', intent: 'WATER_SUPPLY' },

  { text: 'ration card par anaj nahi mila kotedar mana kar raha hai', intent: 'RATION_CARD' },
  { text: 'ration card mein naam judwana hai bete ka', intent: 'RATION_CARD' },
  { text: 'kotedar ration kam deta hai anaj poora nahi milta', intent: 'RATION_CARD' },
  { text: 'ration card apply kiya tha abhi tak nahi bana', intent: 'RATION_CARD' },

  { text: 'manrega ka kaam kiya par mazdoori nahi mili', intent: 'MGNREGA_WAGES' },
  { text: 'job card par mazdoori 30 din se pending hai', intent: 'MGNREGA_WAGES' },
  { text: 'narega mein kaam chahiye job card bhi banwana hai', intent: 'MGNREGA_WAGES' },
  { text: 'mgnrega muster roll par hazri thi par paisa nahi aaya', intent: 'MGNREGA_WAGES' },

  { text: 'awas yojana ki kist nahi aayi ghar adhura hai', intent: 'HOUSING_SCHEME' },
  { text: 'pm awas mein naam judwana hai kaccha makan hai', intent: 'HOUSING_SCHEME' },
  { text: 'awas list mein naam nahi aaya survey hua tha', intent: 'HOUSING_SCHEME' },
  { text: 'pmay gramin instalment is pending for the house', intent: 'HOUSING_SCHEME' },

  { text: 'gaon mein bijli nahi hai transformer kharab hai', intent: 'ELECTRICITY' },
  { text: 'bijli ka bill galat aaya meter kharab hai', intent: 'ELECTRICITY' },
  { text: 'bijli connection ke liye apply kiya tha abhi tak nahi laga', intent: 'ELECTRICITY' },
  { text: 'no electricity since two days the transformer burnt', intent: 'ELECTRICITY' },

  { text: 'aay praman patra ke liye apply kiya tha nahi mila', intent: 'CERTIFICATE' },
  { text: 'jaati praman patra banwana hai tehsil se', intent: 'CERTIFICATE' },
  { text: 'niwas aur aay praman patra dono chahiye', intent: 'CERTIFICATE' },
  { text: 'income and caste certificate application is pending', intent: 'CERTIFICATE' },

  { text: 'padosi medh hata raha hai jameen ka vivad hai', intent: 'LAND_DISPUTE' },
  { text: 'bhai ke saath batwara nahi hua jhagda chal raha hai', intent: 'LAND_DISPUTE' },
  { text: 'jameen par kabza ho gaya padosi mana nahi raha', intent: 'LAND_DISPUTE' },
  { text: 'neighbour encroached on my field it is a boundary dispute', intent: 'LAND_DISPUTE' },

  { text: 'ayushman card hai par aspatal ilaj nahi kar raha', intent: 'HEALTH_CARE' },
  { text: 'aspatal mein dawa nahi mili doctor nahi tha', intent: 'HEALTH_CARE' },
  { text: 'ayushman card banwana hai ilaj ke liye', intent: 'HEALTH_CARE' },
  { text: 'hospital did not admit us under the ayushman card', intent: 'HEALTH_CARE' },
];

/* -------------------------------------------------------------- tokenisation */

/**
 * Devanagari to roman for the domain words that matter. This is the layer that
 * lets one model serve all three scripts: a Hindi sentence and its Hinglish
 * transliteration reduce to the same features, so an 80-line corpus does the work
 * of a much larger one.
 */
const TRANSLIT: Record<string, string> = {
  'पेंशन': 'pension', 'नहीं': 'nahi', 'आ': 'aa', 'रही': 'rahi', 'है': 'hai',
  'महीने': 'mahina', 'महीना': 'mahina', 'से': 'se', 'चार': '4', 'तीन': '3',
  'दो': '2', 'एक': '1', 'पांच': '5', 'पाँच': '5', 'साल': 'saal', 'दिन': 'din',
  'भूमि': 'jameen', 'जमीन': 'jameen', 'रिकॉर्ड': 'record', 'में': 'mein',
  'नाम': 'naam', 'गलत': 'galat', 'सुधार': 'sudhar', 'करवाना': 'karwana',
  'हैंडपंप': 'handpump', 'खराब': 'kharab', 'पानी': 'paani', 'की': 'ki',
  'समस्या': 'samasya', 'राशन': 'ration', 'कार्ड': 'card', 'जुड़ा': 'juda',
  'जुड़वाना': 'judwana', 'मनरेगा': 'manrega', 'मजदूरी': 'mazdoori', 'मिली': 'mili',
  'आवास': 'awas', 'योजना': 'yojana', 'बिजली': 'bijli', 'ट्रांसफार्मर': 'transformer',
  'जन्म': 'janm', 'प्रमाण': 'praman', 'पत्र': 'patra', 'बनवाना': 'banwana',
  'बच्चे': 'bachche', 'का': 'ka', 'पड़ोसी': 'padosi', 'विवाद': 'vivad',
  'आयुष्मान': 'ayushman', 'बना': 'bana', 'इलाज': 'ilaj', 'कराना': 'karana',
  'पैसा': 'paisa', 'खाता': 'khata', 'बैंक': 'bank', 'अस्पताल': 'aspatal',
  'बंद': 'band', 'हो': 'ho', 'गया': 'gaya', 'गयी': 'gayi', 'मेरा': 'mera',
  'मेरी': 'meri', 'चाहिए': 'chahiye', 'हफ्ते': 'hafta', 'सप्ताह': 'hafta',
  'गाँव': 'gaon', 'गांव': 'gaon', 'पर': 'par', 'को': 'ko', 'और': 'aur',
};

/** Spelling variants collapse to one feature. Real text is spelled every way. */
const SPELLING: Record<string, string> = {
  nahin: 'nahi', nai: 'nahi', nhi: 'nahi',
  maheene: 'mahina', mahine: 'mahina', month: 'mahina', months: 'mahina',
  years: 'saal', year: 'saal', varsh: 'saal',
  days: 'din', day: 'din',
  weeks: 'hafta', week: 'hafta', hafte: 'hafta',
  paise: 'paisa', rupaye: 'paisa', rupees: 'paisa', money: 'paisa',
  khate: 'khata', account: 'khata',
  mgnrega: 'manrega', nrega: 'manrega', narega: 'manrega', mnrega: 'manrega',
  pmay: 'awas', housing: 'awas', house: 'ghar', makan: 'ghar',
  water: 'paani', electricity: 'bijli', light: 'bijli', power: 'bijli',
  certificate: 'praman',
  wages: 'mazdoori', wage: 'mazdoori', mazduri: 'mazdoori',
  land: 'jameen', zameen: 'jameen', jamin: 'jameen',
  dispute: 'vivad', jhagda: 'vivad', quarrel: 'vivad', vivaad: 'vivad',
  hospital: 'aspatal', treatment: 'ilaj',
  stopped: 'band',
};

/** Function words that carry no signal but crowd out the explanation. */
const STOPWORDS = new Set([
  'hai', 'hain', 'ho', 'hua', 'the', 'is', 'are', 'a', 'an', 'to', 'of', 'in', 'on',
  'mein', 'ka', 'ki', 'ke', 'se', 'ko', 'par', 'aur', 'and', 'for', 'my', 'our',
  'i', 'we', 'it', 'that', 'this', 'raha', 'rahi', 'gaya', 'gayi', 'diya', 'liya',
  'kar', 'karna', 'hun', 'tha', 'thi', 'bhi', 'hi', 'toh', 'ne', 'not', 'no', 'has',
  // Pure filler. Left in, 'aa' surfaces as a top explanatory feature, which makes the
  // "words that decided it" panel look careless even when the call is right.
  'aa', 'aata', 'raho', 'liye', 'par',
]);

export function tokenize(text: string): string[] {
  return text
    .toLowerCase()
    .replace(/[.,!?;:()"'/\\-]/g, ' ')
    .split(/\s+/)
    .filter(Boolean)
    .map((t) => TRANSLIT[t] ?? t)
    .map((t) => SPELLING[t] ?? t)
    .filter((t) => !STOPWORDS.has(t));
}

/* ------------------------------------------------------------ the classifier */

export interface TrainedModel {
  vocab: string[];
  /** log P(class) */
  logPrior: Record<IntentId, number>;
  /** log P(token | class), Laplace-smoothed */
  logLik: Record<IntentId, Record<string, number>>;
  /** log P(a token never seen for this class), the smoothing floor */
  logFloor: Record<IntentId, number>;
  docs: number;
  /** milliseconds the training actually took, measured on this device */
  trainMs: number;
}

const ALPHA = 1; // Laplace smoothing

/** Count, smooth, take logs. This is the whole of the training step. */
export function trainClassifier(corpus = CORPUS): TrainedModel {
  const t0 = performance.now();

  const docCount = {} as Record<IntentId, number>;
  const tokenCount = {} as Record<IntentId, Record<string, number>>;
  const tokenTotal = {} as Record<IntentId, number>;
  const vocabSet = new Set<string>();

  for (const id of INTENT_IDS) {
    docCount[id] = 0;
    tokenCount[id] = {};
    tokenTotal[id] = 0;
  }

  for (const row of corpus) {
    docCount[row.intent] += 1;
    for (const tok of tokenize(row.text)) {
      vocabSet.add(tok);
      tokenCount[row.intent][tok] = (tokenCount[row.intent][tok] || 0) + 1;
      tokenTotal[row.intent] += 1;
    }
  }

  const vocab = Array.from(vocabSet).sort();
  const V = vocab.length;

  const logPrior = {} as Record<IntentId, number>;
  const logLik = {} as Record<IntentId, Record<string, number>>;
  const logFloor = {} as Record<IntentId, number>;

  for (const id of INTENT_IDS) {
    logPrior[id] = Math.log(docCount[id] / corpus.length);
    const denom = tokenTotal[id] + ALPHA * V;
    logFloor[id] = Math.log(ALPHA / denom);
    logLik[id] = {};
    for (const tok of vocab) {
      logLik[id][tok] = Math.log(((tokenCount[id][tok] || 0) + ALPHA) / denom);
    }
  }

  return { vocab, logPrior, logLik, logFloor, docs: corpus.length, trainMs: performance.now() - t0 };
}

export interface Classification {
  intent: IntentId;
  confidence: number;
  /** every class, best first */
  ranked: { intent: IntentId; logScore: number; prob: number }[];
  tokens: string[];
  known: string[];
  /** words the model has never seen: the honest measure of being out of distribution */
  oov: string[];
  oovRate: number;
  /** the tokens that moved the decision, as log-odds against the runner-up */
  evidence: { token: string; logOdds: number }[];
  threshold: number;
}

export const AUTO_THRESHOLD = 0.62;

/**
 * Two calibration constants, and they were fitted rather than guessed.
 *
 * Raw Naive Bayes sums log-likelihoods over tokens, which saturates the softmax at
 * 1.000 on any sentence longer than a few words, a confidence of "100%" that means
 * nothing. Dividing by the token count over-corrects the other way and flattens
 * everything to ~20%. Normalising by sqrt(n) sits between the two, and the
 * temperature then sets how sharply the remaining gap is read.
 *
 * Both were swept against the corpus: these values put in-distribution complaints
 * around 80-93% and out-of-distribution input under 40%, i.e. on opposite sides of
 * the auto-route threshold, which is the only property that actually matters here.
 */
const LENGTH_EXPONENT = 0.5;
const TEMPERATURE = 0.6;

export function classify(model: TrainedModel, text: string): Classification {
  const tokens = tokenize(text);
  const vocab = new Set(model.vocab);
  const known = tokens.filter((t) => vocab.has(t));
  const oov = tokens.filter((t) => !vocab.has(t));
  const oovRate = tokens.length ? oov.length / tokens.length : 1;

  const norm = known.length ? Math.pow(known.length, LENGTH_EXPONENT) : 1;
  const scored = INTENT_IDS.map((id) => {
    let sum = 0;
    for (const t of known) sum += model.logLik[id][t] ?? model.logFloor[id];
    const logScore = (model.logPrior[id] + (known.length ? sum / norm : 0)) / TEMPERATURE;
    return { intent: id, logScore };
  });

  const max = Math.max(...scored.map((s) => s.logScore));
  const exps = scored.map((s) => Math.exp(s.logScore - max));
  const sumExp = exps.reduce((a, b) => a + b, 0);
  const ranked = scored
    .map((s, i) => ({ ...s, prob: exps[i] / sumExp }))
    .sort((a, b) => b.prob - a.prob);

  // Calibration. An unqualified 0.94 on a two-word sentence would be a lie, so the
  // raw softmax is discounted by out-of-vocabulary share and by how little evidence
  // there was to begin with.
  const evidencePenalty = known.length === 0 ? 0 : Math.min(1, known.length / 3);
  const confidence = ranked[0].prob * (1 - 0.5 * oovRate) * evidencePenalty;

  const top = ranked[0].intent;
  const runnerUp = ranked[1]?.intent ?? top;
  const evidence = Array.from(new Set(known))
    .map((token) => ({
      token,
      logOdds:
        (model.logLik[top][token] ?? model.logFloor[top]) -
        (model.logLik[runnerUp][token] ?? model.logFloor[runnerUp]),
    }))
    .sort((a, b) => b.logOdds - a.logOdds)
    .slice(0, 6);

  return {
    intent: top, confidence, ranked, tokens, known, oov, oovRate,
    evidence, threshold: AUTO_THRESHOLD,
  };
}

/* ---------------------------------------------------------------- evaluation */

export interface LooResult {
  correct: number;
  total: number;
  accuracy: number;
  ms: number;
  misses: { text: string; want: IntentId; got: IntentId; confidence: number }[];
  /** share of misses the confidence gate would have caught anyway */
  missesCaughtByGate: number;
}

/**
 * Leave-one-out cross-validation, run for real when you press the button.
 *
 * It retrains the model 120 times, each time holding one example out, and classifies
 * the held-out line. This is the only number in the demo that says how good the model
 * actually is, and the second number matters more than the first: of the lines it got
 * wrong, how many did the confidence gate refuse to auto-route anyway. A model that is
 * wrong and knows it is a different product from one that is wrong and confident.
 */
export function leaveOneOut(corpus = CORPUS): LooResult {
  const t0 = performance.now();
  let correct = 0;
  let caught = 0;
  const misses: LooResult['misses'] = [];

  for (let i = 0; i < corpus.length; i++) {
    const held = corpus[i];
    const m = trainClassifier(corpus.filter((_, j) => j !== i));
    const r = classify(m, held.text);
    if (r.intent === held.intent) {
      correct += 1;
    } else {
      if (r.confidence < AUTO_THRESHOLD) caught += 1;
      misses.push({ text: held.text, want: held.intent, got: r.intent, confidence: r.confidence });
    }
  }

  return {
    correct,
    total: corpus.length,
    accuracy: correct / corpus.length,
    ms: performance.now() - t0,
    misses,
    missesCaughtByGate: caught,
  };
}

/* ------------------------------------------------------------------ entities */

export interface Entity {
  kind: 'duration' | 'amount' | 'document' | 'scheme';
  label: string;
  value: string;
}

export interface Entities {
  list: Entity[];
  durationDays?: number;
  amount?: number;
  documents: string[];
  schemes: string[];
}

const NUMBER_WORDS: Record<string, number> = {
  ek: 1, do: 2, teen: 3, char: 4, panch: 5, chhe: 6, che: 6, saat: 7, aath: 8,
  nau: 9, das: 10, one: 1, two: 2, three: 3, four: 4, five: 5, six: 6, seven: 7,
  eight: 8, nine: 9, ten: 10,
};

const UNIT_DAYS: Record<string, number> = { din: 1, hafta: 7, mahina: 30, saal: 365 };

const DOCUMENT_TERMS: Record<string, string> = {
  aadhaar: 'Aadhaar', aadhar: 'Aadhaar', adhaar: 'Aadhaar',
  ration: 'Ration card', khata: 'Bank account', passbook: 'Bank passbook',
  job: 'Job card', khatauni: 'Khatauni', khasra: 'Khasra', patta: 'Patta',
  ayushman: 'Ayushman card', voter: 'Voter ID', epic: 'Voter ID',
  praman: 'Certificate', muster: 'Muster roll',
};

const SCHEME_TERMS: Record<string, string> = {
  vridha: 'IGNOAPS (old-age pension)', buzurg: 'IGNOAPS (old-age pension)',
  vidhwa: 'IGNWPS (widow pension)', widow: 'IGNWPS (widow pension)',
  manrega: 'MGNREGA', awas: 'PMAY-Gramin', kisan: 'PM-KISAN',
  ayushman: 'Ayushman Bharat', jal: 'Jal Jeevan Mission',
};

export function extractEntities(text: string): Entities {
  const toks = text
    .toLowerCase()
    .replace(/[.,!?;:]/g, ' ')
    .split(/\s+/)
    .filter(Boolean)
    .map((t) => TRANSLIT[t] ?? t)
    .map((t) => SPELLING[t] ?? t);

  const list: Entity[] = [];
  let durationDays: number | undefined;
  let amount: number | undefined;
  const documents: string[] = [];
  const schemes: string[] = [];

  for (let i = 0; i < toks.length; i++) {
    const t = toks[i];

    // "3 mahina", "teen mahina", "10 din"
    const unit = UNIT_DAYS[t];
    if (unit && i > 0) {
      const prev = toks[i - 1];
      const n = /^\d+$/.test(prev) ? parseInt(prev, 10) : NUMBER_WORDS[prev];
      if (n) {
        const days = n * unit;
        if (durationDays === undefined || days > durationDays) durationDays = days;
        list.push({ kind: 'duration', label: 'How long', value: `${n} × ${t} = ${days} days` });
      }
    }

    // "rs 2000", "₹2,000", "paisa 2000"
    const money = t.match(/^(?:rs\.?|₹)?(\d[\d,]{2,})$/);
    if (money && (/^(?:rs|₹)/.test(t) || toks[i - 1] === 'paisa' || toks[i - 1] === 'rs')) {
      const v = parseInt(money[1].replace(/,/g, ''), 10);
      amount = v;
      list.push({ kind: 'amount', label: 'Amount', value: `₹${v.toLocaleString('en-IN')}` });
    }

    const doc = DOCUMENT_TERMS[t];
    if (doc && !documents.includes(doc)) {
      documents.push(doc);
      list.push({ kind: 'document', label: 'Document named', value: doc });
    }

    const sch = SCHEME_TERMS[t];
    if (sch && !schemes.includes(sch)) {
      schemes.push(sch);
      list.push({ kind: 'scheme', label: 'Scheme named', value: sch });
    }
  }

  return { list, durationDays, amount, documents, schemes };
}

/* ------------------------------------------------------------------ citizens */

export interface Citizen {
  id: string;
  name: string;
  hindi: string;
  avatar: string;
  age: number;
  gender: 'F' | 'M';
  village: string;
  tongue: string;
  widow: boolean;
  household: 'Antyodaya' | 'BPL' | 'APL';
  landHectares: number;
  jobCard: boolean;
  /** the account exists AND is Aadhaar-seeded: the usual point of failure */
  aadhaarSeeded: boolean;
  bankAccount: boolean;
  houseType: 'kutcha' | 'pucca';
  seccListed: boolean;
  /** months since the annual life certificate was filed; past 12 the pension suspends */
  lifeCertificateMonthsAgo: number;
  /** what this citizen actually walks in and says */
  opening: string;
}

export const CITIZENS: Citizen[] = [
  {
    id: 'kamla', name: 'Kamla Devi', hindi: 'कमला देवी', avatar: '👵', age: 67, gender: 'F',
    village: 'Rampur', tongue: 'Awadhi / Hindi', widow: true, household: 'BPL',
    landHectares: 0.4, jobCard: false, aadhaarSeeded: false, bankAccount: true,
    houseType: 'kutcha', seccListed: true, lifeCertificateMonthsAgo: 4,
    opening: 'vidhwa pension nahi aa rahi 3 mahine se, khate mein paisa nahi aaya',
  },
  {
    id: 'phoolwati', name: 'Phoolwati Devi', hindi: 'फूलवती देवी', avatar: '👩🏾‍🦳', age: 72, gender: 'F',
    village: 'Rampur', tongue: 'Awadhi', widow: true, household: 'Antyodaya',
    landHectares: 0, jobCard: false, aadhaarSeeded: true, bankAccount: true,
    houseType: 'kutcha', seccListed: true, lifeCertificateMonthsAgo: 14,
    opening: 'गाँव का हैंडपंप खराब है, पानी की समस्या है',
  },
  {
    id: 'ramesh', name: 'Ramesh Yadav', hindi: 'रमेश यादव', avatar: '🧑‍🌾', age: 38, gender: 'M',
    village: 'Rampur', tongue: 'Hindi', widow: false, household: 'APL',
    landHectares: 1.2, jobCard: true, aadhaarSeeded: true, bankAccount: true,
    houseType: 'pucca', seccListed: false, lifeCertificateMonthsAgo: 0,
    opening: 'khatauni mein mera naam galat likha hai, sudhar karwana hai',
  },
  {
    id: 'sunita', name: 'Sunita Kumari', hindi: 'सुनीता कुमारी', avatar: '👩🏽', age: 29, gender: 'F',
    village: 'Basantpur', tongue: 'Bhojpuri / Hindi', widow: false, household: 'Antyodaya',
    landHectares: 0, jobCard: true, aadhaarSeeded: false, bankAccount: false,
    houseType: 'kutcha', seccListed: true, lifeCertificateMonthsAgo: 0,
    opening: 'manrega ki mazdoori nahi mili 40 din se, muster roll mein hazri chadhi thi',
  },
  {
    id: 'abdul', name: 'Abdul Rahman', hindi: 'अब्दुल रहमान', avatar: '🧔🏽', age: 54, gender: 'M',
    village: 'Basantpur', tongue: 'Urdu / Hindi', widow: false, household: 'BPL',
    landHectares: 0.2, jobCard: false, aadhaarSeeded: true, bankAccount: true,
    houseType: 'kutcha', seccListed: false, lifeCertificateMonthsAgo: 0,
    opening: 'kaccha makan hai, awas yojana ki list mein naam nahi hai',
  },
  {
    id: 'jitender', name: 'Jitender Singh', hindi: 'जितेन्द्र सिंह', avatar: '👨🏽', age: 45, gender: 'M',
    village: 'Rampur', tongue: 'Hindi', widow: false, household: 'APL',
    landHectares: 3.5, jobCard: false, aadhaarSeeded: true, bankAccount: true,
    houseType: 'pucca', seccListed: false, lifeCertificateMonthsAgo: 0,
    opening: 'padosi ne meri jameen par kabza kar liya, medh ko lekar jhagda hai',
  },
];

/* --------------------------------------------------------- the checks engine */

export type CheckStatus = 'pass' | 'fail' | 'unknown';

export interface CheckResult {
  id: string;
  label: string;
  status: CheckStatus;
  detail: string;
}

export interface SchemeVerdict {
  id: string;
  name: string;
  ministry: string;
  checks: CheckResult[];
  verdict: 'eligible' | 'not-eligible' | 'needs-verification';
}

interface SchemeDef {
  id: string;
  name: string;
  ministry: string;
  intents: IntentId[];
  rules: ((c: Citizen) => CheckResult)[];
}

const ok = (id: string, label: string, detail: string): CheckResult => ({ id, label, status: 'pass', detail });
const no = (id: string, label: string, detail: string): CheckResult => ({ id, label, status: 'fail', detail });
const unk = (id: string, label: string, detail: string): CheckResult => ({ id, label, status: 'unknown', detail });

const SCHEMES: SchemeDef[] = [
  {
    id: 'ignoaps', name: 'IGNOAPS: old-age pension', ministry: 'Rural Development',
    intents: ['PENSION_FAILURE'],
    rules: [
      (c) => (c.age >= 60
        ? ok('age', 'Age 60 or above', `${c.age} years on record`)
        : no('age', 'Age 60 or above', `${c.age} years`)),
      (c) => (c.household !== 'APL'
        ? ok('bpl', 'Below-poverty-line household', `${c.household} household`)
        : no('bpl', 'Below-poverty-line household', 'APL household')),
      (c) => (c.bankAccount
        ? ok('bank', 'Bank account on file', 'Account present')
        : no('bank', 'Bank account on file', 'No account on record')),
      (c) => (c.aadhaarSeeded
        ? ok('seed', 'Account Aadhaar-seeded (DBT ready)', 'Seeding confirmed in the NPCI mapper')
        : no('seed', 'Account Aadhaar-seeded (DBT ready)', 'NPCI mapper shows no seeding, so every DBT credit will bounce')),
      (c) => (c.lifeCertificateMonthsAgo <= 12
        ? ok('life', 'Life certificate within 12 months', `Filed ${c.lifeCertificateMonthsAgo} months ago`)
        : no('life', 'Life certificate within 12 months', `Last filed ${c.lifeCertificateMonthsAgo} months ago, lapsed`)),
    ],
  },
  {
    id: 'ignwps', name: 'IGNWPS: widow pension', ministry: 'Rural Development',
    intents: ['PENSION_FAILURE'],
    rules: [
      (c) => (c.widow
        ? ok('widow', 'Widow on record', 'Status recorded')
        : no('widow', 'Widow on record', 'Not recorded as a widow')),
      (c) => (c.age >= 40 && c.age <= 79
        ? ok('age', 'Age 40 to 79', `${c.age} years`)
        : no('age', 'Age 40 to 79', `${c.age} years, outside the band`)),
      (c) => (c.household !== 'APL'
        ? ok('bpl', 'Below-poverty-line household', `${c.household} household`)
        : no('bpl', 'Below-poverty-line household', 'APL household')),
    ],
  },
  {
    id: 'mgnrega', name: 'MGNREGA: 100 days of guaranteed work', ministry: 'Rural Development',
    intents: ['MGNREGA_WAGES'],
    rules: [
      (c) => (c.age >= 18
        ? ok('adult', 'Adult rural resident', `${c.age} years, ${c.village}`)
        : no('adult', 'Adult rural resident', 'Under 18')),
      (c) => (c.jobCard
        ? ok('jobcard', 'Job card issued', 'Job card active')
        : no('jobcard', 'Job card issued', 'No job card, and the Act requires one within 15 days of demand')),
      (c) => (c.bankAccount
        ? ok('bank', 'Wage account for direct credit', 'Account present')
        : no('bank', 'Wage account for direct credit', 'No account, so wages cannot be credited at all')),
      () => unk('attendance', 'Attendance verified on the muster roll', 'The muster roll is a paper record at the worksite, not in this database'),
    ],
  },
  {
    id: 'pmayg', name: 'PMAY-G: rural housing', ministry: 'Rural Development',
    intents: ['HOUSING_SCHEME'],
    rules: [
      (c) => (c.houseType === 'kutcha'
        ? ok('kutcha', 'Currently in a kutcha house', 'Kutcha, per the housing survey')
        : no('kutcha', 'Currently in a kutcha house', 'A pucca house is recorded')),
      (c) => (c.seccListed
        ? ok('secc', 'On the SECC permanent wait list', 'Listed')
        : no('secc', 'On the SECC permanent wait list', 'Not listed, so the route is an Awas+ survey appeal')),
      (c) => (c.landHectares <= 2.5
        ? ok('land', 'Landholding within the limit', `${c.landHectares} ha`)
        : no('land', 'Landholding within the limit', `${c.landHectares} ha, above the limit`)),
      () => unk('other', 'No other pucca house in the family', 'Requires a field visit by the Awas Supervisor'),
    ],
  },
  {
    id: 'nfsa', name: 'NFSA: subsidised food grain', ministry: 'Consumer Affairs & Food',
    intents: ['RATION_CARD'],
    rules: [
      (c) => (c.household !== 'APL'
        ? ok('priority', 'Priority / Antyodaya household', `${c.household}`)
        : no('priority', 'Priority / Antyodaya household', 'APL, outside the NFSA net')),
      (c) => (c.aadhaarSeeded
        ? ok('aadhaar', 'All members Aadhaar-linked', 'Linked')
        : unk('aadhaar', 'All members Aadhaar-linked', 'The household roster is incomplete in this record')),
    ],
  },
  {
    id: 'ayushman', name: 'Ayushman Bharat: ₹5 lakh cover', ministry: 'Health & Family Welfare',
    intents: ['HEALTH_CARE'],
    rules: [
      (c) => (c.seccListed || c.household !== 'APL'
        ? ok('secc', 'SECC deprivation criteria met', `${c.household}${c.seccListed ? ', SECC listed' : ''}`)
        : no('secc', 'SECC deprivation criteria met', 'Neither SECC-listed nor below poverty line')),
      () => unk('card', 'Ayushman card generated', 'Card status lives with the State Health Agency, not this record'),
    ],
  },
  {
    id: 'jjm', name: 'Jal Jeevan Mission: tap water', ministry: 'Jal Shakti',
    intents: ['WATER_SUPPLY'],
    rules: [
      (c) => ok('village', 'Village covered under JJM', `${c.village} is a sanctioned habitation`),
      (c) => ok('habitation', 'Complaint is within the sanctioned scope', `Drinking water for ${c.village} is a JJM obligation, not a discretionary favour`),
    ],
  },
];

export function evaluateSchemes(intent: IntentId, c: Citizen): SchemeVerdict[] {
  return SCHEMES.filter((s) => s.intents.includes(intent)).map((s) => {
    const checks = s.rules.map((r) => r(c));
    const anyFail = checks.some((x) => x.status === 'fail');
    const anyUnknown = checks.some((x) => x.status === 'unknown');
    const verdict: SchemeVerdict['verdict'] = anyFail
      ? 'not-eligible'
      : anyUnknown
        ? 'needs-verification'
        : 'eligible';
    return { id: s.id, name: s.name, ministry: s.ministry, checks, verdict };
  });
}

export interface Finding {
  status: 'problem' | 'ok' | 'unknown';
  label: string;
  detail: string;
  /**
   * An unknown only blocks routing when nobody downstream is going to resolve it.
   * "Is the handpump actually broken" is unknown, but it is also precisely the job
   * being dispatched, and treating it as a blocker would mean a human has to approve
   * every water complaint, which is how good gates turn into rubber stamps.
   */
  blocking?: boolean;
}

/**
 * Root-cause probes. The product's real job is not "which scheme is she in", because she
 * already knows that. It is "why has the money stopped", which is nearly always a
 * plumbing failure two systems away from her.
 */
export function diagnose(intent: IntentId, c: Citizen, e: Entities): Finding[] {
  const f: Finding[] = [];

  if (intent === 'PENSION_FAILURE') {
    f.push(
      c.aadhaarSeeded
        ? { status: 'ok', label: 'Bank account is Aadhaar-seeded', detail: 'The DBT route is intact.' }
        : {
            status: 'problem', label: 'Bank account is not Aadhaar-seeded',
            detail: 'The DBT credit has nowhere to land. This alone explains a stopped pension, and it is fixed at the bank branch, not at the welfare office she was sent to.',
          },
    );
    f.push(
      c.lifeCertificateMonthsAgo > 12
        ? {
            status: 'problem', label: 'Annual life certificate has lapsed',
            detail: `Last filed ${c.lifeCertificateMonthsAgo} months ago. Disbursal auto-suspends past 12 months.`,
          }
        : { status: 'ok', label: 'Life certificate is current', detail: `Filed ${c.lifeCertificateMonthsAgo} months ago.` },
    );
    if (e.durationDays && e.durationDays >= 60) {
      f.push({
        status: 'problem', label: `Arrears accruing for ${Math.round(e.durationDays / 30)} months`,
        detail: 'Arrears are payable from the date of suspension once the block clears, but they have to be claimed. Nothing pays them out on its own.',
      });
    }
  }

  if (intent === 'MGNREGA_WAGES') {
    if (!c.bankAccount) {
      f.push({ status: 'problem', label: 'No wage account on file', detail: 'Wages cannot be credited at all. This is upstream of any payment delay.' });
    }
    if (!c.jobCard) {
      f.push({ status: 'problem', label: 'No job card issued', detail: 'Without a job card there is no legal record that work was ever demanded.' });
    }
    if (e.durationDays && e.durationDays > 15) {
      f.push({
        status: 'problem', label: `Payment overdue by ${e.durationDays} days`,
        detail: 'Past 15 days the Act itself owes delay compensation at 0.05% per day. That claim should be filed alongside the wage claim, and almost never is.',
      });
    }
    f.push({ status: 'unknown', label: 'Fund Transfer Order status at the block', detail: 'Whether the FTO was generated and rejected is only visible inside NREGASoft, which is the first thing the Programme Officer will open.' });
  }

  if (intent === 'HOUSING_SCHEME') {
    if (!c.seccListed) {
      f.push({
        status: 'problem', label: 'Not on the SECC permanent wait list',
        detail: 'This is the binding constraint. The route is an Awas+ survey appeal through the Gram Sabha, not another fresh application.',
      });
    }
    if (c.houseType === 'pucca') {
      f.push({ status: 'unknown', blocking: true, label: 'Record contradicts the claim: it shows a pucca house', detail: 'One of the two is wrong, and forwarding either version would be a decision. Needs field verification first.' });
    }
  }

  if (intent === 'WATER_SUPPLY' || intent === 'ELECTRICITY') {
    f.push({ status: 'unknown', label: 'Physical asset condition', detail: 'No record can tell you whether a handpump or a transformer is actually broken. This needs an engineer on site, and the SLA is written around that.' });
    f.push({ status: 'problem', label: 'Affects the whole habitation, not one household', detail: 'Filed as a community complaint: it escalates automatically if unresolved, and the resolution is posted publicly.' });
  }

  if (intent === 'LAND_DISPUTE') {
    f.push({ status: 'unknown', blocking: true, label: 'Two parties, contested facts', detail: 'Only one side has been heard. The engine may summarise the claim and pull the revenue record. That is the end of its remit.' });
  }

  if (intent === 'LAND_RECORD_ERROR') {
    f.push({ status: 'unknown', label: 'Original deed must be compared against the record', detail: 'Correcting a khatauni entry is a revenue-officer act with legal consequence.' });
  }

  if (intent === 'CERTIFICATE' || intent === 'RATION_CARD' || intent === 'HEALTH_CARE') {
    if (!c.aadhaarSeeded) {
      f.push({ status: 'problem', label: 'Aadhaar linkage incomplete', detail: 'Almost every counter asks for this first, and turns people away for it.' });
    }
    f.push({ status: 'unknown', label: 'Supporting documents not yet collected', detail: 'The application can be drafted now and completed at the counter.' });
  }

  return f;
}

/* ------------------------------------------------------------------- routing */

export interface Routing {
  department: string;
  officer: string;
  slaDays: number;
  priority: 'routine' | 'high' | 'urgent';
  /** true only when every gate below passed */
  autoRoutable: boolean;
  /** why a human must sign this off; empty means the engine may proceed alone */
  humanReasons: string[];
  escalation: string;
}

export function routeCase(
  intent: IntentId,
  cls: Classification,
  c: Citizen,
  verdicts: SchemeVerdict[],
  findings: Finding[],
): Routing {
  const meta = INTENTS[intent];
  const humanReasons: string[] = [];

  if (meta.neverAutomatic) {
    humanReasons.push('Policy gate: this case class is never decided by software. Two parties, contested facts, and a decision that changes who owns what.');
  }
  if (cls.confidence < AUTO_THRESHOLD) {
    humanReasons.push(`Confidence gate: ${(cls.confidence * 100).toFixed(0)}% is below the ${(AUTO_THRESHOLD * 100).toFixed(0)}% auto-route threshold.`);
  }
  if (cls.oovRate > 0.4) {
    humanReasons.push(`Vocabulary gate: ${Math.round(cls.oovRate * 100)}% of the words are outside the model's vocabulary, so it is guessing more than reading.`);
  }
  // Evidence gate. Only unknowns that nobody downstream will resolve count, because an
  // unknown the receiving officer is being dispatched to answer is not a blocker.
  const unknowns =
    verdicts.flatMap((v) => v.checks).filter((x) => x.status === 'unknown').length +
    findings.filter((f) => f.status === 'unknown' && f.blocking).length;
  if (unknowns > 0) {
    humanReasons.push(`Evidence gate: ${unknowns} check${unknowns === 1 ? '' : 's'} bearing on the decision could not be resolved from the record. A person has to establish the facts first.`);
  }

  // Adverse-finding gate. The engine may carry a claim forward on its own. It may
  // never be the thing that records a refusal: a rejection needs a name against it.
  const refusals = verdicts.filter((v) => v.verdict === 'not-eligible');
  if (refusals.length > 0) {
    humanReasons.push(`Adverse-finding gate: ${refusals.length} entitlement check${refusals.length === 1 ? ' came' : 's came'} back negative (${refusals.map((r) => r.name.split(': ')[0]).join(', ')}). Software may forward a claim; it may not be the thing that says no.`);
  }

  // Urgency is a policy decision, not a model output.
  let priority: Routing['priority'] = 'routine';
  if (intent === 'WATER_SUPPLY' || intent === 'HEALTH_CARE') priority = 'urgent';
  else if (intent === 'ELECTRICITY' || intent === 'MGNREGA_WAGES') priority = 'high';
  else if (intent === 'PENSION_FAILURE' && c.age >= 70) priority = 'high';

  return {
    department: meta.department,
    officer: meta.officer,
    slaDays: meta.slaDays,
    priority,
    autoRoutable: humanReasons.length === 0,
    humanReasons,
    escalation: `Unresolved past ${meta.slaDays} days → auto-escalates to the Block Development Officer and appears on the public overdue board.`,
  };
}

/* ------------------------------------------------------------------ drafting */

export interface Draft {
  subject: string;
  body: string[];
  annexures: string[];
  /** what the assistant says back to the citizen, in her own register */
  spoken: string;
}

export function draftApplication(
  c: Citizen,
  intent: IntentId,
  e: Entities,
  verdicts: SchemeVerdict[],
  findings: Finding[],
): Draft {
  const meta = INTENTS[intent];
  const problems = findings.filter((f) => f.status === 'problem');
  const eligible = verdicts.filter((v) => v.verdict === 'eligible');
  const blocked = verdicts.filter((v) => v.verdict === 'not-eligible');

  const body: string[] = [];
  body.push(`${c.name}, aged ${c.age}, resident of ${c.village} (${c.household} household), reports: ${meta.label.toLowerCase()}.`);
  if (e.durationDays) {
    body.push(`Duration reported by the applicant: ${e.durationDays} days, i.e. about ${Math.round(e.durationDays / 30)} month(s).`);
  }
  if (problems.length) {
    body.push(`Record check identifies ${problems.length} probable cause${problems.length === 1 ? '' : 's'}: ${problems.map((p) => p.label.toLowerCase()).join('; ')}.`);
  }
  if (eligible.length) {
    body.push(`Entitlement confirmed against: ${eligible.map((v) => v.name).join(', ')}.`);
  }
  if (blocked.length) {
    body.push(`Not eligible under: ${blocked.map((v) => v.name).join(', ')}. Reasons annexed.`);
  }
  body.push('Relief sought: restoration of the entitlement together with arrears from the date of interruption, and a written reason if declined.');

  const annexures = [
    'Aadhaar (masked)',
    ...(c.bankAccount ? ['Bank passbook, first page'] : []),
    ...(intent === 'PENSION_FAILURE' ? ['Pension sanction order (PPO)', 'Life certificate'] : []),
    ...(intent === 'MGNREGA_WAGES' ? ['Job card copy', 'Muster roll extract'] : []),
    ...(intent === 'HOUSING_SCHEME' ? ['Photograph of the existing house', 'Awas+ survey acknowledgement'] : []),
    ...(intent === 'LAND_RECORD_ERROR' ? ['Khatauni extract', 'Original deed'] : []),
    'Gram Panchayat receipt for this application',
  ];

  const spoken = problems.length
    ? `${c.name} ji, ${meta.hindi}. सबसे संभावित कारण: ${problems[0].label}. Aavedan taiyaar hai; panchayat sadasya ki manzoori ke baad ${meta.department} ko chala jayega, aur aapko receipt number mil jayega.`
    : `${c.name} ji, aapka mamla ${meta.department} ke paas jayega. Aavedan taiyaar hai, receipt number aaj hi mil jayega.`;

  return { subject: `${meta.label}: ${c.name}, ${c.village} (Ward 04)`, body, annexures, spoken };
}

/* --------------------------------------------------- the public case ledger */

export type CaseStatus = 'filed' | 'in-progress' | 'resolved';
export type CaseDecision =
  | 'auto-routed'
  | 'approved'
  | 'reclassified'
  | 'documents-requested'
  | 'held-for-hearing';

export const DECISION_LABEL: Record<CaseDecision, string> = {
  'auto-routed': 'Auto-routed by the engine',
  approved: 'Approved by a panchayat member',
  reclassified: 'Reclassified by a panchayat member',
  'documents-requested': 'Documents requested first',
  'held-for-hearing': 'Held for a Gram Sabha hearing',
};

export interface CaseRecord {
  id: string;
  citizenName: string;
  village: string;
  intent: IntentId;
  confidence: number;
  department: string;
  slaDays: number;
  priority: Routing['priority'];
  decision: CaseDecision;
  decidedBy: string;
  status: CaseStatus;
  filedAt: number;
  note?: string;
  prevHash: string;
  hash: string;
}

export function caseId(n: number): string {
  return `PK-2047-${String(n).padStart(4, '0')}`;
}

/**
 * Every decision is sealed with a real SHA-256 over its contents plus the previous
 * case's hash, the same tamper-evidence the voting centre uses, pointed at the
 * thing that actually gets abused in a panchayat: who decided what, and when.
 */
export async function sealCase(rec: Omit<CaseRecord, 'hash'>): Promise<CaseRecord> {
  const payload = [
    rec.id, rec.citizenName, rec.village, rec.intent, rec.confidence.toFixed(4),
    rec.department, rec.slaDays, rec.priority, rec.decision, rec.decidedBy,
    rec.status, rec.filedAt, rec.note ?? '', rec.prevHash,
  ].join('|');
  const hash = await sha256(payload);
  return { ...rec, hash };
}
